#USA GEONAMES PER LA GRECIA


library(progress)
country <- "GR"
colnames(pc2020_EL_NUTS.2021_v1.0)<-c("NUTS3", "PCode")
pc2020_EL_NUTS.2021_v1.0 <- pc2020_EL_NUTS.2021_v1.0[-1,]

data_or <- data
data_pc <- geonames_GR
data_nuts <- pc2020_EL_NUTS.2021_v1.0

levels(as.factor(data_pc$admin.name1[which(data_pc$country.code == country)]))
levels(as.factor(data_pc$admin.name2[which(data_pc$country.code == country)]))
levels(as.factor(data_pc$admin.name3[which(data_pc$country.code == country)]))

indices <- which(data_or$country == country)

data_or$region <- tolower(data_or$region)
data_or$city <- tolower(data_or$city)
data_pc$admin.name1 <- tolower(data_pc$admin.name1)
data_or$city <- gsub(" ", "", data_or$city)
data_or$city <- gsub("-", "", data_or$city)
data_or$region <- gsub(" ", "", data_or$region)
data_or$region <- gsub("-", "", data_or$region)
data_pc$admin.name1 <- gsub(" ", "", data_pc$admin.name1)
data_pc$admin.name1 <- gsub("-", "", data_pc$admin.name1)

regions <- levels(as.factor(data_pc$admin.name1))


data_or$region[which(data_or$region=="athens")]<-"attica"
data_or$region[which(data_or$region=="athens,attica")]<-"attica"
data_or$region[which(data_or$region=="attiki")]<-"attica"
data_or$region[which(data_or$region=="attika")]<-"attica"
data_or$region[which(data_or$region=="kentrikimakedonia")]<-"centralmacedonia"
data_or$region[which(data_or$region=="westernmacedonia")]<-"westmacedonia"
data_or$region[which(data_or$region=="eastmacedoniaandthrace")]<-"eastmacedoniathrace"
data_or$region[which(data_or$region=="thrace")]<-"eastmacedoniathrace"
data_or$region[which(data_or$region=="thessaloniki")]<-"centralmacedonia"
data_or$region[which(data_or$region=="chalkidiki")]<-"centralmacedonia"
data_or$region[which(data_or$region=="achaia")]<-"westerngreece"
data_or$region[which(data_or$region=="patras")]<-"westerngreece"
data_or$region[which(data_or$region=="lesvos")]<-"voreioaigaio"
data_or$region[which(data_or$region=="samos")]<-"voreioaigaio"
data_or$region[which(data_or$region=="viotia")]<-"stereaellada"
data_or$region[which(data_or$region=="kavala")]<-"eastmacedoniathrace"


data_or$region[which(data_or$city=="ioannina")]<-"epirus"
data_or$city[which(data_or$city=="ioannina")]<-"epirus"
data_or$region[which(data_or$city=="preveza")]<-"epirus"
data_or$city[which(data_or$city=="preveza")]<-"epirus"
data_or$region[which(data_or$city=="arta")]<-"epirus"
data_or$city[which(data_or$city=="arta")]<-"epirus"
data_or$region[which(data_or$city=="igoumenitsa")]<-"epirus"
data_or$city[which(data_or$city=="igoumenitsa")]<-"epirus"
data_or$region[which(data_or$city=="rethimno")]<-"crete"
data_or$city[which(data_or$city=="rethimno")]<-"crete"
data_or$region[which(data_or$city=="heraklion")]<-"crete"
data_or$city[which(data_or$city=="heraklion")]<-"crete"
data_or$region[which(data_or$city=="iraklio")]<-"crete"
data_or$city[which(data_or$city=="iraklio")]<-"crete"
data_or$region[which(data_or$city=="irakleio")]<-"crete"
data_or$city[which(data_or$city=="irakleio")]<-"crete"
data_or$region[which(data_or$city=="creta")]<-"crete"
data_or$city[which(data_or$city=="creta")]<-"crete"
data_or$region[which(data_or$city=="heraklion,crete")]<-"crete"
data_or$city[which(data_or$city=="heraklion,crete")]<-"crete"
data_or$region[which(data_or$city=="heraklioncrete")]<-"crete"
data_or$city[which(data_or$city=="heraklioncrete")]<-"crete"
data_or$region[which(data_or$city=="herakleion")]<-"crete"
data_or$city[which(data_or$city=="herakleion")]<-"crete"
data_or$region[which(data_or$city=="heraklio")]<-"crete"
data_or$city[which(data_or$city=="heraklio")]<-"crete"
data_or$region[which(data_or$city=="agiosnikolaos")]<-"crete"
data_or$city[which(data_or$city=="agiosnikolaos")]<-"crete"
data_or$region[which(data_or$city=="chania")]<-"crete"
data_or$city[which(data_or$city=="chania")]<-"crete"
data_or$region[which(data_or$city=="rethymnon")]<-"crete"
data_or$city[which(data_or$city=="rethymnon")]<-"crete"
data_or$region[which(data_or$city=="iraklion")]<-"crete"
data_or$city[which(data_or$city=="iraklion")]<-"crete"
data_or$region[which(data_or$city=="rethymno")]<-"crete"
data_or$city[which(data_or$city=="rethymno")]<-"crete"
data_or$region[which(data_or$city=="kerkyra")]<-"ionianislands"
data_or$city[which(data_or$city=="kerkyra")]<-"ionianislands"
data_or$region[which(data_or$city=="corfu")]<-"ionianislands"
data_or$city[which(data_or$city=="corfu")]<-"ionianislands"
data_or$region[which(data_or$city=="lefkada")]<-"ionianislands"
data_or$city[which(data_or$city=="lefkada")]<-"ionianislands"
data_or$region[which(data_or$city=="argostoli")]<-"ionianislands"
data_or$city[which(data_or$city=="argostoli")]<-"ionianislands"
data_or$region[which(data_or$city=="zakynthos")]<-"ionianislands"
data_or$city[which(data_or$city=="zakynthos")]<-"ionianislands"
data_or$region[which(data_or$city=="agiaparaskevi")]<-"attica"
data_or$city[which(data_or$city=="agiaparaskevi")]<-"attica"
data_or$region[which(data_or$city=="agiaparaskeue")]<-"attica"
data_or$city[which(data_or$city=="agiaparaskeue")]<-"attica"
data_or$region[which(data_or$city=="atenas")]<-"attica"
data_or$region[which(data_or$city=="peiraias")]<-"attica"
data_or$city[which(data_or$city=="peiraias")]<-"attica"
data_or$region[which(data_or$city=="pireas")]<-"attica"
data_or$city[which(data_or$city=="pireas")]<-"attica"
data_or$region[which(data_or$city=="piraeus")]<-"attica"
data_or$city[which(data_or$city=="piraeus")]<-"attica"
data_or$region[which(data_or$city=="pireaus")]<-"attica"
data_or$city[which(data_or$city=="pireaus")]<-"attica"
data_or$region[which(data_or$city=="athinon")]<-"attica"
data_or$city[which(data_or$city=="athinon")]<-"attica"
data_or$region[which(data_or$city=="holargos")]<-"attica"
data_or$city[which(data_or$city=="holargos")]<-"attica"
data_or$region[which(data_or$city=="magoula")]<-"attica"
data_or$city[which(data_or$city=="magoula")]<-"attica"
data_or$region[which(data_or$city=="athens")]<-"attica"
data_or$city[which(data_or$city=="athens")]<-"attica"
data_or$region[which(data_or$city=="î'î~î-î\u009dî'")]<-"attica"
data_or$region[which(data_or$city=="athã¨nes")]<-"attica"
data_or$region[which(data_or$city=="athen")]<-"attica"
data_or$city[which(data_or$city=="î'î¸î®î½î±")]<-"attica"
data_or$city[which(data_or$city=="athen")]<-"attica"
data_or$region[which(data_or$city=="athens,greece")]<-"attica"
data_or$city[which(data_or$city=="athens,greece")]<-"attica"
data_or$region[which(data_or$city=="athens,")]<-"attica"
data_or$city[which(data_or$city=="athens,")]<-"attica"
data_or$region[which(data_or$city=="athensgreece")]<-"attica"
data_or$city[which(data_or$city=="athensgreece")]<-"attica"
data_or$region[which(data_or$city=="athena")]<-"attica"
data_or$city[which(data_or$city=="athena")]<-"attica"
data_or$region[which(data_or$city=="zografou")]<-"attica"
data_or$city[which(data_or$city=="zografou")]<-"attica"
data_or$region[which(data_or$city=="pikermi")]<-"attica"
data_or$city[which(data_or$city=="pikermi")]<-"attica"
data_or$region[which(data_or$city=="voula")]<-"attica"
data_or$city[which(data_or$city=="voula")]<-"attica"
data_or$region[which(data_or$city=="zografos")]<-"attica"
data_or$city[which(data_or$city=="zografos")]<-"attica"
data_or$region[which(data_or$city=="zografoycampus,athens")]<-"attica"
data_or$city[which(data_or$city=="zografoycampus,athens")]<-"attica"
data_or$region[which(data_or$city=="marousi")]<-"attica"
data_or$city[which(data_or$city=="marousi")]<-"attica"
data_or$region[which(data_or$city=="glyfada")]<-"attica"
data_or$city[which(data_or$city=="glyfada")]<-"attica"
data_or$region[which(data_or$city=="elefsis")]<-"attica"
data_or$city[which(data_or$city=="elefsis")]<-"attica"
data_or$region[which(data_or$city=="elefsina")]<-"attica"
data_or$city[which(data_or$city=="elefsina")]<-"attica"
data_or$region[which(data_or$city=="vari")]<-"attica"
data_or$city[which(data_or$city=="vari")]<-"attica"
data_or$region[which(data_or$city=="spetes")]<-"attica"
data_or$city[which(data_or$city=="spetes")]<-"attica"
data_or$region[which(data_or$city=="anavyssos")]<-"attica"
data_or$city[which(data_or$city=="anavyssos")]<-"attica"
data_or$region[which(data_or$city=="dekelia")]<-"attica"
data_or$city[which(data_or$city=="dekelia")]<-"attica"
data_or$region[which(data_or$city=="anavissos")]<-"attica"
data_or$city[which(data_or$city=="anavissos")]<-"attica"
data_or$region[which(data_or$city=="chalandri")]<-"attica"
data_or$city[which(data_or$city=="chalandri")]<-"attica"
data_or$region[which(data_or$city=="dafni")]<-"attica"
data_or$city[which(data_or$city=="dafni")]<-"attica"
data_or$region[which(data_or$city=="dafni,athens")]<-"attica"
data_or$city[which(data_or$city=="dafni,athens")]<-"attica"
data_or$region[which(data_or$city=="egaleo")]<-"attica"
data_or$city[which(data_or$city=="egaleo")]<-"attica"
data_or$region[which(data_or$city=="aigaleoathens")]<-"attica"
data_or$city[which(data_or$city=="aigaleoathens")]<-"attica"
data_or$region[which(data_or$city=="aegaleo")]<-"attica"
data_or$city[which(data_or$city=="aegaleo")]<-"attica"
data_or$region[which(data_or$city=="aigã¡leo")]<-"attica"
data_or$region[which(data_or$city=="lamia")]<-"stereaellada"
data_or$city[which(data_or$city=="lamia")]<-"stereaellada"
data_or$region[which(data_or$city=="larissa")]<-"thessaly"
data_or$city[which(data_or$city=="larissa")]<-"thessaly"
data_or$region[which(data_or$city=="larisa")]<-"thessaly"
data_or$city[which(data_or$city=="larisa")]<-"thessaly"
data_or$region[which(data_or$city=="volos")]<-"thessaly"
data_or$city[which(data_or$city=="volos")]<-"thessaly"
data_or$region[which(data_or$city=="trikala")]<-"thessaly"
data_or$city[which(data_or$city=="trikala")]<-"thessaly"
data_or$region[which(data_or$city=="karditsa")]<-"thessaly"
data_or$city[which(data_or$city=="karditsa")]<-"thessaly"
data_or$region[which(data_or$city=="pã¡trai")]<-"westerngreece"
data_or$region[which(data_or$city=="patras")]<-"westerngreece"
data_or$city[which(data_or$city=="patras")]<-"westerngreece"
data_or$region[which(data_or$city=="akrata")]<-"westerngreece"
data_or$city[which(data_or$city=="akrata")]<-"westerngreece"
data_or$region[which(data_or$city=="pyrgos")]<-"westerngreece"
data_or$city[which(data_or$city=="pyrgos")]<-"westerngreece"
data_or$region[which(data_or$city=="rio")]<-"westerngreece"
data_or$city[which(data_or$city=="rio")]<-"westerngreece"
data_or$region[which(data_or$city=="patra")]<-"westerngreece"
data_or$city[which(data_or$city=="patra")]<-"westerngreece"
data_or$region[which(data_or$city=="aigio")]<-"westerngreece"
data_or$city[which(data_or$city=="aigio")]<-"westerngreece"
data_or$region[which(data_or$city=="agrinio")]<-"westerngreece"
data_or$city[which(data_or$city=="agrinio")]<-"westerngreece"
data_or$region[which(data_or$city=="amaliada")]<-"westerngreece"
data_or$city[which(data_or$city=="amaliada")]<-"westerngreece"
data_or$region[which(data_or$city=="messolonghi")]<-"westerngreece"
data_or$city[which(data_or$city=="messolonghi")]<-"westerngreece"
data_or$region[which(data_or$city=="drama")]<-"eastmacedoniathrace"
data_or$city[which(data_or$city=="drama")]<-"eastmacedoniathrace"
data_or$region[which(data_or$city=="xanthi")]<-"eastmacedoniathrace"
data_or$city[which(data_or$city=="xanthi")]<-"eastmacedoniathrace"
data_or$region[which(data_or$city=="alexandroupolis")]<-"eastmacedoniathrace"
data_or$city[which(data_or$city=="alexandroupolis")]<-"eastmacedoniathrace"
data_or$region[which(data_or$city=="alexandroupoli")]<-"eastmacedoniathrace"
data_or$city[which(data_or$city=="alexandroupoli")]<-"eastmacedoniathrace"
data_or$region[which(data_or$city=="komotini")]<-"eastmacedoniathrace"
data_or$city[which(data_or$city=="komotini")]<-"eastmacedoniathrace"
data_or$region[which(data_or$city=="kavala")]<-"eastmacedoniathrace"
data_or$city[which(data_or$city=="kavala")]<-"eastmacedoniathrace"
data_or$region[which(data_or$city=="orestiada")]<-"eastmacedoniathrace"
data_or$city[which(data_or$city=="orestiada")]<-"eastmacedoniathrace"
data_or$region[which(data_or$city=="mytilene,lesvosisland")]<-"voreioaigaio"
data_or$city[which(data_or$city=="mytilene,lesvosisland")]<-"voreioaigaio"
data_or$region[which(data_or$city=="mytilenelesvosisland")]<-"voreioaigaio"
data_or$city[which(data_or$city=="mytilenelesvosisland")]<-"voreioaigaio"
data_or$region[which(data_or$city=="mytilene,lesvos")]<-"voreioaigaio"
data_or$city[which(data_or$city=="mytilene,lesvos")]<-"voreioaigaio"
data_or$region[which(data_or$city=="mytilene,lesbos")]<-"voreioaigaio"
data_or$city[which(data_or$city=="mytilene,lesbos")]<-"voreioaigaio"
data_or$region[which(data_or$city=="lesvos")]<-"voreioaigaio"
data_or$city[which(data_or$city=="lesvos")]<-"voreioaigaio"
data_or$region[which(data_or$city=="karlovasi")]<-"voreioaigaio"
data_or$city[which(data_or$city=="karlovasi")]<-"voreioaigaio"
data_or$region[which(data_or$city=="mytilene")]<-"voreioaigaio"
data_or$city[which(data_or$city=="mytilene")]<-"voreioaigaio"
data_or$region[which(data_or$city=="mytilini")]<-"voreioaigaio"
data_or$city[which(data_or$city=="mytilini")]<-"voreioaigaio"
data_or$region[which(data_or$city=="mytileni")]<-"voreioaigaio"
data_or$city[which(data_or$city=="mytileni")]<-"voreioaigaio"
data_or$region[which(data_or$city=="samos")]<-"voreioaigaio"
data_or$city[which(data_or$city=="samos")]<-"voreioaigaio"
data_or$region[which(data_or$city=="chios")]<-"voreioaigaio"
data_or$city[which(data_or$city=="chios")]<-"voreioaigaio"
data_or$region[which(data_or$city=="myrina")]<-"voreioaigaio"
data_or$city[which(data_or$city=="myrina")]<-"voreioaigaio"
data_or$region[which(data_or$city=="lemnos")]<-"voreioaigaio"
data_or$city[which(data_or$city=="lemnos")]<-"voreioaigaio"
data_or$region[which(data_or$city=="kozani")]<-"westmacedonia"
data_or$city[which(data_or$city=="kozani")]<-"westmacedonia"
data_or$region[which(data_or$city=="kastoria")]<-"westmacedonia"
data_or$city[which(data_or$city=="kastoria")]<-"westmacedonia"
data_or$region[which(data_or$city=="grevena")]<-"westmacedonia"
data_or$city[which(data_or$city=="grevena")]<-"westmacedonia"
data_or$region[which(data_or$city=="florina")]<-"westmacedonia"
data_or$city[which(data_or$city=="florina")]<-"westmacedonia"
data_or$region[which(data_or$city=="epanomi")]<-"westmacedonia"
data_or$city[which(data_or$city=="epanomi")]<-"westmacedonia"
data_or$region[which(data_or$city=="serres")]<-"centralmacedonia"
data_or$city[which(data_or$city=="serres")]<-"centralmacedonia"
data_or$region[which(data_or$city=="veria")]<-"centralmacedonia"
data_or$city[which(data_or$city=="veria")]<-"centralmacedonia"
data_or$region[which(data_or$city=="veroia")]<-"centralmacedonia"
data_or$city[which(data_or$city=="veroia")]<-"centralmacedonia"
data_or$region[which(data_or$city=="katerini")]<-"centralmacedonia"
data_or$city[which(data_or$city=="katerini")]<-"centralmacedonia"
data_or$region[which(data_or$city=="kilkis")]<-"centralmacedonia"
data_or$city[which(data_or$city=="kilkis")]<-"centralmacedonia"
data_or$region[which(data_or$city=="salonica")]<-"centralmacedonia"
data_or$city[which(data_or$city=="salonica")]<-"centralmacedonia"
data_or$region[which(data_or$city=="thessalonki")]<-"centralmacedonia"
data_or$region[which(data_or$city=="thessaloniki")]<-"centralmacedonia"
data_or$city[which(data_or$city=="thessaloniki")]<-"centralmacedonia"
data_or$region[which(data_or$city=="thermithessaloniki")]<-"centralmacedonia"
data_or$city[which(data_or$city=="thermithessaloniki")]<-"centralmacedonia"
data_or$region[which(data_or$city=="thessalonike")]<-"centralmacedonia"
data_or$city[which(data_or$city=="thessalonike")]<-"centralmacedonia"
data_or$region[which(data_or$city=="thermi")]<-"centralmacedonia"
data_or$city[which(data_or$city=="thermi")]<-"centralmacedonia"
data_or$region[which(data_or$city=="yiannitsa")]<-"centralmacedonia"
data_or$city[which(data_or$city=="yiannitsa")]<-"centralmacedonia"
data_or$region[which(data_or$city=="giannitsa")]<-"centralmacedonia"
data_or$city[which(data_or$city=="giannitsa")]<-"centralmacedonia"
data_or$region[which(data_or$city=="edessa")]<-"centralmacedonia"
data_or$city[which(data_or$city=="edessa")]<-"centralmacedonia"
data_or$region[which(data_or$city=="rhodes")]<-"northaegean"
data_or$city[which(data_or$city=="rhodes")]<-"northaegean"
data_or$region[which(data_or$city=="rhodesisland")]<-"northaegean"
data_or$city[which(data_or$city=="rhodesisland")]<-"northaegean"
data_or$region[which(data_or$city=="rodos")]<-"northaegean"
data_or$city[which(data_or$city=="rodos")]<-"northaegean"
data_or$region[which(data_or$city=="ermoupolis")]<-"northaegean"
data_or$city[which(data_or$city=="ermoupolis")]<-"northaegean"
data_or$region[which(data_or$city=="ermoupoli")]<-"northaegean"
data_or$city[which(data_or$city=="ermoupoli")]<-"northaegean"
data_or$region[which(data_or$city=="syros")]<-"northaegean"
data_or$city[which(data_or$city=="syros")]<-"northaegean"
data_or$region[which(data_or$city=="siros")]<-"northaegean"
data_or$city[which(data_or$city=="siros")]<-"northaegean"
data_or$region[which(data_or$city=="ermoupolis,syros")]<-"northaegean"
data_or$city[which(data_or$city=="ermoupolis,syros")]<-"northaegean"
data_or$region[which(data_or$city=="hermoupolis,syros")]<-"northaegean"
data_or$city[which(data_or$city=="hermoupolis,syros")]<-"northaegean"
data_or$region[which(data_or$city=="hermoupolis")]<-"northaegean"
data_or$city[which(data_or$city=="hermoupolis")]<-"northaegean"
data_or$region[which(data_or$city=="kalamata")]<-"peloponnese"
data_or$city[which(data_or$city=="kalamata")]<-"peloponnese"
data_or$region[which(data_or$city=="tripoli")]<-"peloponnese"
data_or$city[which(data_or$city=="tripoli")]<-"peloponnese"
data_or$region[which(data_or$city=="tripolis")]<-"peloponnese"
data_or$city[which(data_or$city=="tripolis")]<-"peloponnese"
data_or$region[which(data_or$city=="korinthos")]<-"peloponnese"
data_or$city[which(data_or$city=="korinthos")]<-"peloponnese"
data_or$region[which(data_or$city=="corinth")]<-"peloponnese"
data_or$city[which(data_or$city=="corinth")]<-"peloponnese"
data_or$region[which(data_or$city=="corinthos")]<-"peloponnese"
data_or$city[which(data_or$city=="corinthos")]<-"peloponnese"
data_or$region[which(data_or$city=="sparta")]<-"peloponnese"
data_or$city[which(data_or$city=="sparta")]<-"peloponnese"
data_or$region[which(data_or$city=="spata")]<-"peloponnese"
data_or$city[which(data_or$city=="spata")]<-"peloponnese"
data_or$region[which(data_or$city=="sparti")]<-"peloponnese"
data_or$city[which(data_or$city=="sparti")]<-"peloponnese"
data_or$region[which(data_or$city=="nafplio")]<-"peloponnese"
data_or$city[which(data_or$city=="nafplio")]<-"peloponnese"
data_or$region[which(data_or$city=="chalkida")]<-"stereaellada"
data_or$city[which(data_or$city=="chalkida")]<-"stereaellada"
data_or$region[which(data_or$city=="chalcis")]<-"stereaellada"
data_or$city[which(data_or$city=="chalcis")]<-"stereaellada"
data_or$region[which(data_or$city=="psahna")]<-"stereaellada"
data_or$city[which(data_or$city=="psahna")]<-"stereaellada"
data_or$region[which(data_or$city=="domokos")]<-"stereaellada"
data_or$city[which(data_or$city=="domokos")]<-"stereaellada"
data_or$region[which(data_or$city=="thiva")]<-"stereaellada"
data_or$city[which(data_or$city=="thiva")]<-"stereaellada"
data_or$region[which(data_or$city=="chalkis")]<-"stereaellada"
data_or$city[which(data_or$city=="chalkis")]<-"stereaellada"
data_or$region[which(data_or$city=="kos")]<-"stereaellada"
data_or$city[which(data_or$city=="kos")]<-"stereaellada"
data_or$region[which(data_or$city=="amfissa")]<-"stereaellada"
data_or$city[which(data_or$city=="amfissa")]<-"stereaellada"
data_or$region[which(data_or$city=="oinofyta")]<-"stereaellada"
data_or$city[which(data_or$city=="oinofyta")]<-"stereaellada"

manuals <- data.frame(cbind(Region = c("Region"), City = c("City"), ID = c("ID")))

pb <- progress_bar$new(total=length(indices))
pb$tick(0)

for(i in indices){
  ind2 <- intersect(data_or[i,5], regions)
  if(length(ind2) != 0 && ind2 != ""){
    code <- data_pc$postal.code[which(data_pc$admin.name1==data_or[i,5])]
    data_or$NUTS3[i] <- data_nuts$NUTS3[which(data_nuts$PCode==code)]
  }
  else{
    ind3 <- intersect(data_or[i,6], regions)
    if(length(ind3) != 0 && ind3 != ""){
      code <- data_pc$postal.code[which(data_pc$admin.name1==data_or[i,6])]
      data_or$NUTS3[i] <- data_nuts$NUTS3[which(data_nuts$PCode==code)]
    }
  }
  
  if(data_or$NUTS3[i]=="None"){
    manuals <- rbind(manuals, c(data_or$region[i], data_or$city[i], i))
  }
  pb$tick()
}

#levels(as.factor(data$NUTS3))
#manuals

#last second corrections

data_or$NUTS3[as.numeric(manuals$ID[which(manuals$City=="zografou,athens")])] <- "EL304"
data_or$NUTS3[as.numeric(manuals$ID[which(manuals$City=="athensmarousi")])] <- "EL304"

data$NUTS3[indices] <- data_or$NUTS3[indices]
save(data, file="C:/Users/user/Desktop/forORCID/ORCID_2021_activities_extract_uptoGR.RData")
